//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upravljanje_Flotom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servi
    {
        public int IDServis { get; set; }
        public string Naziv { get; set; }
        public string Detalji { get; set; }
        public Nullable<double> Cijena { get; set; }
        public Nullable<int> VoziloID { get; set; }
    }
}
